#Deriving the latest base image
FROM python:3.9

# Any working directory can be chosen as per choice like '/' or '/home' etc
WORKDIR /usr/app/src

#to COPY the remote file at working directory in container
COPY script_integ.py ./


RUN set -xe \
    && apt-get update \
    && apt-get install -y python3-pip
RUN pip install --upgrade pip
RUN pip install requests
RUN pip install Pillow
RUN pip install numpy
RUN pip install tensorflow==2.9.2

#CMD instruction should be used to run the software
#contained by your image, along with any arguments.
CMD [ "python", "./script_integ.py"]